swagger: '2.0'
info:
  title: Bank Argent transactions API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/profile/transactions:
    get:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Transactions API
      description: API for fetching Transactions for the ongoing month and separated per bank accounts
      parameters:
        - in: header
          type: string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: User transactions for the ongoing month retrieved Successfully
          schema:
            $ref: '#/definitions/MonthlyTransactionsResponse'
        '204':
          description: The server successfully processed the request but is not returning any content
        '400':
          description: Bad Request. Invalid Fields or Authorization token not provided.
        '401':
          description: Unauthorized. Invalid or expired Authorization token.
        '500':
          description: Internal Server Error

  /user/profile/transactions/{id}:
    get:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Transaction Details API
      description: API for fetching details of a specific transaction
      parameters:
        - in: header
          type: string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: path
          type: string
          name: id
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: Transaction details retrieved Successfully
          schema:
            $ref: '#/definitions/TransactionDetailsResponse'
        '204':
          description: The server successfully processed the request but is not returning any content
        '400':
          description: Bad Request. Invalid Fields or Authorization token not provided.
        '401':
          description: Unauthorized. Invalid or expired Authorization token.
        '404':
          description: Not Found. Transaction not found.
        '500':
          description: Internal Server Error

  /user/profile/transactions/{id}/edit:
    patch:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: Edit User Transaction API
      description: API for editing user transaction information
      parameters:
        - in: header
          type: string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: path
          type: string
          name: id
          required: true
        - in: body
          name: Edition
          description: Update user transaction information
          required: true
          schema:
            $ref: '#/definitions/TransactionEdition'
      produces:
        - application/json
      responses:
        '200':
          description: User transaction edited successfully
          schema:
            $ref: '#/definitions/TransactionEditionResponse'
        '400':
          description: Bad Request. Invalid Fields or Authorization token not provided.
        '401':
          description: Unauthorized. Invalid or expired Authorization token.
        '404':
          description: Not Found. Transaction not found.
        '500':
          description: Internal Server Error

securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header

definitions:
  MonthlyTransactionsResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: array
        items:
          type: object
          properties:
            month:
              type: string
            bankAccount:
              type: string
            transactions:
              type: array
              items:
                $ref: '#/definitions/TransactionResponse'

  TransactionDetailsResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        $ref: '#/definitions/TransactionResponse'

  TransactionResponse:
    type: object
    properties:
      id:
        type: integer
      date:
        type: string
      recipient:
        type: object
        properties:
          corporate:
            type: string
          iban:
            type: string
      amount:
        type: integer
      transactionType:
        type: string
      category:
        type: string
      notes:
        type: string

  TransactionEdition:
    type: object
    properties:
      category:
        type: string
      notes:
        type: string

  TransactionEditionResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        $ref: '#/definitions/TransactionResponse'
